//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace billman.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class buildingDetail
    {
        public string buildingCode { get; set; }
        public byte[] floorDetails { get; set; }
        public Nullable<int> flatNo { get; set; }
    
        public virtual building building { get; set; }
        public virtual flatNumber flatNumber { get; set; }
    }
}
