//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace billman.Models.Database
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class employee
    {
        [Required]
        public string name { get; set; }

        [Required]
        public string empId { get; set; }

      [Required]
        public string joinDate { get; set; }

 
        public string resignDate { get; set; }

      [Required]
        public string salary { get; set; }

      [Required]
        public string mobile { get; set; }

        [Required]
        public string usertype { get; set; }
    }
}
