//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace billman.Models.Database
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class subscription
    {
        [Required]
        public string username { get; set; }

        [Required]
        public string paymentstatus { get; set; }

        [Required]
        public string DOP { get; set; }
    
        public virtual user user { get; set; }
    }
}
