//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace billman.Models.Database
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class subUser
    {
        [Required]
        public string colonyCode { get; set; }

        [Required]
        public string buildingCode { get; set; }

        [Required]
        public string flatNumber { get; set; }

        [Required]
        public string name { get; set; }

        [Required]
        public string mobile { get; set; }

        [Required]
        public string members { get; set; }
    
        public virtual building building { get; set; }
    }
}
