//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace billman.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public string name { get; set; }
        public string mobileNumber { get; set; }
        public string address { get; set; }
        public string division { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public string status { get; set; }
        public string username { get; set; }
        public int usertype { get; set; }
    
        public virtual login login { get; set; }
        public virtual subscription subscription { get; set; }
    }
}
