//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace midproject.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class billDetail
    {
        public int id { get; set; }
        public string colonyCode { get; set; }
        public string buildingCode { get; set; }
        public string buildingName { get; set; }
        public string flatNo { get; set; }
        public string floorDetails { get; set; }
        public string flatSize { get; set; }
        public string flatRenterName { get; set; }
        public string wasaBills { get; set; }
        public string wasaBillsstatus { get; set; }
        public string currentBills { get; set; }
        public string currentBillsstatus { get; set; }
        public string flatRents { get; set; }
        public string flatRentsstatus { get; set; }
    
        public virtual building building { get; set; }
        public virtual colony colony { get; set; }
    }
}
