//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace midproject.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class building
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public building()
        {
            this.colonys = new HashSet<colony>();
            this.subUsers = new HashSet<subUser>();
        }
    
        public string colonyCode { get; set; }
        public string username { get; set; }
        public string buildingName { get; set; }
        public string buildingCode { get; set; }
    
        public virtual buildingDetail buildingDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<colony> colonys { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<subUser> subUsers { get; set; }
    }
}
