//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace midproject.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class buildingDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public buildingDetail()
        {
            this.currentBills = new HashSet<currentBill>();
            this.flatRents = new HashSet<flatRent>();
            this.wasaBills = new HashSet<wasaBill>();
        }
    
        public string buildingCode { get; set; }
        public string floorDetails { get; set; }
        public string flatNo { get; set; }
    
        public virtual flatNumber flatNumber { get; set; }
        public virtual building building { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<currentBill> currentBills { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<flatRent> flatRents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<wasaBill> wasaBills { get; set; }
    }
}
