//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace midproject.Models.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class bdatabaseEntities : DbContext
    {
        public bdatabaseEntities()
            : base("name=bdatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<buildingDetail> buildingDetails { get; set; }
        public virtual DbSet<building> buildings { get; set; }
        public virtual DbSet<colony> colonys { get; set; }
        public virtual DbSet<currentBill> currentBills { get; set; }
        public virtual DbSet<flatNumber> flatNumbers { get; set; }
        public virtual DbSet<flatRent> flatRents { get; set; }
        public virtual DbSet<login> logins { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<wasaBill> wasaBills { get; set; }
        public virtual DbSet<employee> employees { get; set; }
        public virtual DbSet<subscription> subscriptions { get; set; }
        public virtual DbSet<subUser> subUsers { get; set; }
    }
}
