//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace midproject.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class flatNumber
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public flatNumber()
        {
            this.buildingDetails = new HashSet<buildingDetail>();
        }
    
        public string flatSize { get; set; }
        public string flatNumber1 { get; set; }
        public string rentStatus { get; set; }
        public string buildingCode { get; set; }
        public string flatRenterName { get; set; }
        public string mobile { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<buildingDetail> buildingDetails { get; set; }
    }
}
