//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace midproject.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class subUser
    {
        public string colonyCode { get; set; }
        public string buildingCode { get; set; }
        public string flatNumber { get; set; }
        public string mobile { get; set; }
        public string members { get; set; }
    
        public virtual building building { get; set; }
        public virtual colony colony { get; set; }
    }
}
